version: '3'
services:
  maildev:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - "2500:25"
      - "8081:80"
  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apistarter
      MYSQL_USER: apistarter
      MYSQL_PASSWORD: apistarter
    ports:
      - "4306:3306"
    command: "mysqld --character-set-server=utf8mb4 --max_allowed_packet=32M"

volumes:
  mysql_data:
