spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/steamuloapistarter
    username: root
    password: root

  mail:
      host: etienne-T1700
      port: 25
      username:
      password:

jwt:
  expiration: 86400000
