database:
  flyway: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/marketpay
    username: root
    password: root

  mail:
      host: etienne-T1700
      port: 25
      username:
      password:

sftp:
  pathIncomming: /home/etienne/workspaceMarketPay/incomming
  pathArchive: /home/etienne/workspaceMarketPay/archive

jwt:
  expiration: 86400000
