spring:
  datasource:
    url: jdbc:mysql://localhost/steamuloapistarter?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

sftp:
  pathIncomming: /home/dle/Documents/SteamuloAPIStarter/incomming
  pathArchive: /home/dle/Documents/SteamuloAPIStarter/archive
