spring:
  datasource:
    url: jdbc:mysql://localhost/SteamuloApiStarter?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
