database:
  flyway: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/marketpay
    username: root
    password: root


  mail:
      host: tchekroun
      port: 25
      username: tchekroun@gmail.com
      password: password

sftp:
  pathIncomming: /Users/tchekroun/workspace/marketpay/incomming
  pathArchive: /Users/tchekroun/workspace/marketpay/archive
