spring:
  datasource:
    url: jdbc:mysql://localhost/steamuloapistarter?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
