database:
  flyway: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/marketpay
    username: root
    password: root

sftp:
  pathIncomming: /home/etienne/workspaceMarketPay/incomming
  pathArchive: /home/etienne/workspaceMarketPay/archive
