database:
  flyway: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/marketpay
    username: kevin
    password: steamulo

sftp:
  pathIncomming: /home/kdidelot/Workspace/carrefour-banque/incomming
  pathArchive: /home/kdidelot/Workspace/carrefour-banque/archive
