server:
  port: 8000

management:
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 5s
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9000

jwt:
  secret: sfpQq=a9HZy@2d_4@Tqf+B5Z#sk?u+cW?ju!-Qs8z!f&sH?Dvu
  expiration: 300000

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    level: "[REQ:%X{req_id:-none}] [USR:%X{user_id:-none}] %5p"
