server:
  port: 8000

management:
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 5s
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9000

jwt:
  secret: sfpQq=a9HZy@2d_4@Tqf+B5Z#sk?u+cW?ju!-Qs8z!f&sH?Dvu
  expiration: 300000

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

spring:
  hazelcast:
    config: classpath:hazelcast.xml
  cache:
    type: hazelcast
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        javax:
          cache:
            provider: com.hazelcast.cache.HazelcastCachingProvider
            missing_cache_strategy: create
        cache:
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_second_level_cache: true
          use_query_cache: true
          use_minimal_puts: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    level: "[REQ:%X{req_id:-none}] [USR:%X{user_id:-none}] %5p"
