server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

jwt:
  secret: sfpQq=a9HZy@2d_4@Tqf+B5Z#sk?u+cW?ju!-Qs8z!f&sH?Dvu
  expiration: 300000

security:
  sessions: stateless

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

flyway:
  enabled: true
  locations: classpath:db/migration

spring:
  metrics:
    export:
      enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg %n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: logs/application.log
