#debug: true
#logging.level.com.pcv: DEBUG

environment: dev

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/dev
  datasource:
    url: jdbc:mysql://localhost:4306/apistarter?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: apistarter
    password: apistarter
  mail:
    host: localhost
    port: 2500
