server:
  port: 8000

management:
  port: 9000

database:
  driver:
  url:
  user:
  password:
  packageName:
  flyway: true


logging:
 level:
  root: INFO
  org:
    springframework:
      web: ERROR
  com:
    concretepage: INFO
