server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

database:
  flyway: true

jwt:
  secret: UnEXV9#C;-q)xa2$=q4?um2[;L-~Hj(6SWw!cW~5f,yLzHv
  expiration: 300000

security:
  sessions: stateless

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

#On n'utilise pas le flyway auto de spring boot
flyway:
  enabled: false

#Intervale de temps entre l'execution de la scheduled task
scheduledTask:
  fixedRate: 120000

spring:
  mail:
    host:
    port:
    username:
    password:

email:
  filter: steamulo.com
  emailFrom: marketpay@steamulo.com
  replyTo: marketpay@steamulo.com
  #signature
  name: Market Pay
  address: rue du Gourio
  postalCodeAndCity: 75009
  country: France
  email: marketpay@steamulo.com
  phoneNumber: +33 1 73 04 13 45

keypass:
  expirationReset: 60
  expirationCreate: 2880
  urlReset: http://localhost:3000/login/key/

