server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

database:
  driver:
  url:
  user:
  password:
  packageName:
  flyway: true

jwt:
  secret: UnEXV9#C;-q)xa2$=q4?um2[;L-~Hj(6SWw!cW~5f,yLzHv

security:
  sessions: stateless
