debug: true
logging.level.com.steamulo: DEBUG
logging.level.org.hibernate.SQL: DEBUG

environment: dev

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/dev
  datasource:
    url: jdbc:mysql://localhost:4306/basejump?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: basejump
    password: basejump
  mail:
    host: localhost
    port: 2500
