server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

jwt:
  secret: UnEXV9#C;-q)xa2$=q4?um2[;L-~Hj(6SWw!cW~5f,yLzHv
  expiration: 300000

security:
  sessions: stateless

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

flyway:
  enabled: true
  locations: classpath:db/migration
