server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

jwt:
  secret: UnEXV9#C;-q)xa2$=q4?um2[;L-~Hj(6SWw!cW~5f,yLzHv
  expiration: 300000

security:
  sessions: stateless

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

flyway:
  enabled: true
  locations: classpath:db/migration

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.web: ERROR
    com.steamulo: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg %n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log
