server:
  port: 8000

management:
  server:
    port: 9000

jwt:
  secret: sfpQq=a9HZy@2d_4@Tqf+B5Z#sk?u+cW?ju!-Qs8z!f&sH?Dvu
  expiration: 300000

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg %n"
