server:
  port: 8000

management:
  port: 9000
  context-path: /manage
  security:
    enabled: false

database:
  flyway: true

jwt:
  secret: UnEXV9#C;-q)xa2$=q4?um2[;L-~Hj(6SWw!cW~5f,yLzHv

security:
  sessions: stateless

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs

#On n'utilise pas le flyway auto de spring boot
flyway:
  enabled: false

sftp:
  host: toto.com
  port: 2222
  user: toto
  password: toto
